<?php
/**
 * Twitter Plugin
 *
 * Lets you show your current Twitter status in your theme, as well
 * as an option automatically post your new posts to Twitter.
 *
 * Example usage in a PHP template:
 * <code>
 * <div id="twitterbox">
 * <img src="<?php echo htmlspecialchars( $tweet_image_url ); ?>">
 * <?php echo htmlspecialchars( $tweet_text ) . ' @ ' . htmlspecialchars( $tweet_time ); ?>
 * </div>
 * </code>
 *
 **/

class Twitter extends Plugin
{
	/**
	 * Required plugin information
	 * @return array The array of information
	 **/
	public function info()
	{
		return array(
			'name' => 'Twitter',
			'version' => '0.5',
			'url' => 'http://habariproject.org/',
			'author' => 'Habari Community',
			'authorurl' => 'http://habariproject.org/',
			'license' => 'Apache License 2.0',
			'description' => 'Twitter plugin for Habari',
			'copyright' => '2008'
		);
	}

	/**
	 * Add update beacon support
	 **/
	public function action_update_check()
	{
	 	Update::add( 'Twitter', 'DD2774BA-96ED-11DC-ABEF-3BAA56D89593', $this->info->version );
	}

	/**
	 * Add actions to the plugin page for this plugin
	 * @param array $actions An array of actions that apply to this plugin
	 * @param string $plugin_id The string id of a plugin, generated by the system
	 * @return array The array of actions to attach to the specified $plugin_id
	 **/
	public function filter_plugin_config( $actions, $plugin_id )
	{
		if ( $plugin_id == $this->plugin_id() ) {
			$actions[]= 'Configure';
		}

		return $actions;
	}

	/**
	 * Respond to the user selecting an action on the plugin page
	 * @param string $plugin_id The string id of the acted-upon plugin
	 * @param string $action The action string supplied via the filter_plugin_config hook
	 **/
	public function action_plugin_ui( $plugin_id, $action )
	{
		if ( $plugin_id == $this->plugin_id() ) {
			switch ( $action ) {
				case 'Configure' :
					$ui= new FormUI( strtolower( get_class( $this ) ) );
					$twitter_username= $ui->add( 'text', 'username', 'Twitter Username:' );
					$twitter_password= $ui->add( 'password', 'password', 'Twitter Password:' );
					$twitter_post= $ui->add( 'select', 'post_status', 'Autopost to Twitter:' );
					$twitter_post->options= array( '0' => 'Disabled', '1' => 'Enabled' );
					$twitter_show= $ui->add( 'select', 'show', 'Make Tweets available to Habari' );
					$twitter_show->options= array( '0' => 'No', '1' => 'Yes' );
					$twitter_cache_time= $ui->add( 'text', 'cache', 'Cache expiry in seconds:' );
					$ui->on_success( array( $this, 'updated_config' ) );
					$ui->out();
					break;
			}
		}
	}

	/**
	 * Returns true if plugin config form values defined in action_plugin_ui should be stored in options by Habari
	 * @return bool True if options should be stored
	 **/
	public function updated_config( $ui )
	{
		return true;
	}

	/**
	 * Post a status to Twitter
	 * @param string $tweet The new status to post
	 * @todo Update to use RemoteRequest when RemoteRequest supports logins to avoid curl dependency
	 **/
	public function post_status( $tweet )
	{
		$username= Options::get( 'twitter:username' );
		$password= Options::get( 'twitter:password' );

		$update_url= 'http://twitter.com/statuses/update.xml';
		$ch= curl_init();

		curl_setopt( $ch, CURLOPT_URL, $update_url );
		curl_setopt( $ch, CURLOPT_CONNECTTIMEOUT, 2 );
		curl_setopt( $ch, CURLOPT_RETURNTRANSFER, 1 );
		curl_setopt( $ch, CURLOPT_POST, 1 );
		curl_setopt( $ch, CURLOPT_POSTFIELDS, 'source=habari&status=' . urlencode( $tweet ) );
		curl_setopt( $ch, CURLOPT_USERPWD, "$username:$password" );

		$ch_buffer= curl_exec( $ch );

		curl_close( $ch );
	}

	/**
	 * React to the update of a post status to 'published'
	 * @param Post $post The post object with the status change
	 * @param int $oldvalue The old status value
	 * @param int $newvalue The new status value
	 **/
	public function action_post_update_status( $post, $oldvalue, $newvalue )
	{
		if ( $newvalue == Post::status( 'published' ) && $newvalue != $oldvalue ) {
			if ( Options::get( 'twitter:post_status' ) == '1' ) {
				$this->post_status( 'New Blog post: ' . $post->title . ' ' . $post->permalink );
			}
		}
	}

	/**
	 * Add last Twitter status, time, and image to the available template vars
	 * @param Theme $theme The theme that will display the template
	 **/
	public function action_add_template_vars( $theme )
	{
		if ( Options::get( 'twitter:show' ) && Options::get( 'twitter:username' ) != '' ) {
			$twitter_url= 'http://twitter.com/statuses/user_timeline/' . urlencode( Options::get( 'twitter:username' ) ) . '.xml?count=1';

			if ( Cache::has( 'twitter_tweet_text' ) && Cache::has( 'twitter_tweet_time' ) && Cache::has( 'tweet_image_url' ) ) {
				$theme->tweet_text= Cache::get( 'twitter_tweet_text' );
				$theme->tweet_time= Cache::get( 'twitter_tweet_time' );
				$theme->tweet_image_url= Cache::get( 'tweet_image_url' );
			}
			else {
				try {
					$response= RemoteRequest::get_contents( $twitter_url );
					$xml= new SimpleXMLElement( $response );
					$theme->tweet_text= (string) $xml->status->text;
					$theme->tweet_time= (string) $xml->status->created_at;
					$theme->tweet_image_url= (string) $xml->status->user->profile_image_url;
					Cache::set( 'twitter_tweet_text', $theme->tweet_text, Options::get( 'twitter:cache' ) );
					Cache::set( 'twitter_tweet_time', $theme->tweet_time, Options::get( 'twitter:cache' ) );
					Cache::set( 'tweet_image_url', $theme->tweet_image_url, Options::get( 'twitter:cache' ) );
				}
				catch ( Exception $e ) {
					$theme->tweet_text= 'Unable to contact Twitter.';
					$theme->tweet_time= '';
					$theme->tweet_image_url= '';
				}
			}
		}
		else {
			$theme->tweet_text= 'Please set your username in the Twitter plugin config.';
			$theme->tweet_time= '';
			$theme->tweet_image_url= '';
		}
	}
}

?>