<?php

class Disqus extends Plugin
{
	/**
	* Provide plugin info to the system
	*/
	public function info()
	{
		return array(
			'name' => 'Disqus',
			'version' => '0.1',
			'url' => 'http://habariproject.org/',
			'author' => 'Habari Community',
			'authorurl' => 'http://habariproject.org/',
			'license' => 'Apache License 2.0',
			'description' => 'Integrates the Disqus comment system',
			'copyright' => '2008',
		);
	}

	/**
	 * On plugin init, add the disqus comments template
	 */
	public function action_init()
	{
		$this->add_template('disqus_comments', dirname(__FILE__) . '/disqus_comments.php');
	}
	/**
	* Add actions to the plugin page for this plugin
	*
	* @param array $actions An array of actions that apply to this plugin
	* @param string $plugin_id The string id of a plugin, generated by the system
	* @return array The array of actions to attach to the specified $plugin_id
	*/

	public function filter_plugin_config($actions, $plugin_id)
	{
		if ($plugin_id == $this->plugin_id())
		{
			$actions[] = _t('Configure');
		}
		return $actions;
	}

	public function action_plugin_ui($plugin_id, $action)
	{
		if ( $plugin_id == $this->plugin_id() ) {
			switch ($action) {
				case _t('Configure'):
					$ui = new FormUI(strtolower(get_class($this)));
					$ui->add('text', 'username', 'Disqus Username:');
					$ui->on_success(array($this, 'updated_config'));
					$ui->out();
				break;
			}
		}
	}

	public function updated_config($ui)
	{
		return true;
	}

	public function theme_comments( $theme, $post )
	{
		$disqus_username= Options::get( strtolower(get_class($this)) . ':username' );
		if ( !$post->info->comment_disabled && $post->comments->count == 0 && $disqus_username ) {
			$theme->disqus_username= $disqus_username;
			$theme->display( 'disqus_comments' );
		}
		else {
			$theme->display( 'comments' );
		}
	}

	/**
	* Registers this plugin for updates against the beacon
	*/
	public function action_update_check()
	{
		Update::add('Disqus', '358e7ee7-ee2f-4b04-80f4-f690129357a6', $this->info->version);
	}

}

?>
