<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0" 
                xmlns:html="http://www.w3.org/TR/REC-html40"
                xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
	<xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
	<xsl:template match="/">
		<html xmlns="http://www.w3.org/1999/xhtml">
			<head>
				<title>XML Sitemap</title>
				<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
				<style type="text/css">
					body {
						font-family:"Lucida Grande","Lucida Sans Unicode",Tahoma,Verdana;
						font-size:13px;
						background-color: #F0F0F0;
						color: #555555;
					}

					a {
						color:#333333;
						text-decoration: none;
					}

					a:hover {
						text-decoration: underline;
					}

					h1 {
						color: #333333;
						margin: 10px auto;
						width: 750px;
					}
					
					.container {
						-moz-border-radius:5px 5px 5px 5px;
						-moz-box-shadow:0 1px 15px #DDDDDD;
						background:none repeat scroll 0 0 #FAFAFA;
						border:1px solid #E7E7E7;
						margin:10px auto;
						padding:15px 40px;
						width:750px;
					}
									
					td {
						font-size:11px;
					}
					
					th {
						color: #333333;
						text-align:left;
					}
					
					tr.odd {
						background-color: #F3F3F3;
					}
					
					#footer {
						margin:10px auto;
						-moz-border-radius:5px 5px 5px 5px;
						background-color: #E3E3E3;
						padding:7px 15px;
						white-space:nowrap;
						font-size:8pt;
						width:240px;
					}
					
					#footer a {
						color:#777777;
						font-weight: bold;
					}
					

				</style>
			</head>
			<body>
				<h1>XML Sitemap</h1>
				<div id="content" class="container">
					<table cellpadding="5">
						<tr>
							<th>URL</th>
							<th>Last Modified</th>
						</tr>
						<xsl:variable name="lower" select="'abcdefghijklmnopqrstuvwxyz'"/>
						<xsl:variable name="upper" select="'ABCDEFGHIJKLMNOPQRSTUVWXYZ'"/>
						<xsl:for-each select="sitemap:urlset/sitemap:url">
							<tr>
								<xsl:if test="position() mod 2 = 1">
									<xsl:attribute  name="class">odd</xsl:attribute>
								</xsl:if>
								<td style="width:610px">
									<xsl:variable name="itemURL">
										<xsl:value-of select="sitemap:loc"/>
									</xsl:variable>
									<a href="{$itemURL}">
										<xsl:value-of select="sitemap:loc"/>
									</a>
								</td>
								<td style="width:110px">
									<xsl:value-of select="concat(substring(sitemap:lastmod,0,11),concat(' ', substring(sitemap:lastmod,12,5)))"/>
								</td>
							</tr>
						</xsl:for-each>
					</table>
				</div>
				<div id="footer">
					Generated by the <a href="http://habariproject.org/dist/plugins/sitemaps/" title="Sitemaps Plugin for Habari">Sitemaps Plugin for Habari</a>.
				</div>
			</body>
		</html>
	</xsl:template>
</xsl:stylesheet>